openfoodfacts/openfoodfacts-ios

OFFWriteAPI.swift

A struct with the available constants for the write api.

OFFWriteAPI added

---

OpenFoodFacts/Views/ProductDetail/Summary/SummaryHeaderTableViewCell.swift
OpenFoodFacts/Views/ProductDetail/Summary/SummaryHeaderTableViewCell.xib

Use NutriscoreView in product summary

---

Sources/Helpers/URLs.swift
Sources/ViewControllers/Settings/SettingsTableViewController.swift
Sources/ViewControllers/User/LoginViewController.swift
Sources/Views/LaunchScreen.storyboard
Sources/Views/Settings/Settings.storyboard
Sources/Views/User/User.storyboard

Added iOS Open Beauty Facts app link for cross promotion, which resolves the Issue #56.
Please review it @teolemon @Tovkal.
Tested on a physical device, to open the App Store.

Add iOS Open Beauty Facts application link

---

OpenFoodFacts.xcodeproj/project.pbxproj
Sources/Helpers/SharingManager.swift
Sources/Helpers/URLs.swift
Sources/Info.plist
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift
Sources/ViewControllers/Products/Detail/Summary/SummaryHeaderCellController.swift
Sources/ViewControllers/Settings/CreditsViewController.swift
Sources/Views/Products/Detail/Summary/SummaryHeaderCellController.xib
Tests/ViewControllers/Products/Detail/ProductDetailViewControllerTests.swift
Tests/ViewControllers/Products/Detail/Summary/SummaryHeaderCellControllerTests.swift

It redirects to the localized version of the openfoodfacts website (I checked on English and Russian). The sharing item is just a link but I can change it to whatever text needed.

Button to share product is added

---

xliff/en.xliff

Translated the Test strings
Edit 1: Does not resolves issue #43 I don't know if those strings should be considered unnecessary or not.

Resolves #78, resolves #79 Translate Test Strings and Remove $(PRODUCT_NAME)

---

OpenFoodFacts.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Sources/en.lproj/Localizable.strings

Changed 'OpenFoodFacts' to 'Open Food Facts'  in the title string

Updated string for issue #100

---

.travis.yml

Changed travis config to build using xcode 10.1 
This fixes the build (but not the tests)

Update travis build for xcode 10.1

---

Tests/Common/ProductServiceMock.swift
Tests/Models/DataManagerSpec.swift
Tests/Network/ProductServiceTests.swift

-  Fixes Issue #122 
-  Fixes Issue #123

Update mocks to the new productApi interface signature

---

Sources/ViewControllers/User/LoggedInViewController.swift
Sources/en.lproj/Localizable.strings

Describe the changes made and why they were made instead of how they were made.
Added an UIAlertViewController for log out confirmation and add new keys to the english localizable file
nil
nil

Logout alert vc and added new keys in localizable file fixes issue 148

---

Sources/Helpers/URLs.swift

Resolves #199 Essentials URL not localised

---

Sources/Localization/fr.lproj/Localizable.strings
Sources/Localization/my.lproj/Localizable.strings
Sources/Localization/nb.lproj/Localizable.strings
Sources/Localization/oc.lproj/Localizable.strings
Sources/Localization/pt.lproj/Localizable.strings
Sources/Localization/ru.lproj/Localizable.strings
Sources/Localization/sco.lproj/Localizable.strings
Sources/Localization/sl.lproj/Localizable.strings
Sources/Localization/sma.lproj/Localizable.strings
Sources/Localization/so.lproj/Localizable.strings
Sources/Localization/ss.lproj/Localizable.strings
Sources/Localization/sv.lproj/Localizable.strings
Sources/Localization/tg.lproj/Localizable.strings
Sources/Localization/tt.lproj/Localizable.strings
Sources/Localization/uk.lproj/Localizable.strings
Sources/Localization/uz.lproj/Localizable.strings
Sources/Localization/ve.lproj/Localizable.strings
Sources/Localization/vi.lproj/Localizable.strings
Sources/Localization/xh.lproj/Localizable.strings
Sources/Localization/zu.lproj/Localizable.strings
Sources/Views/Settings/Settings.storyboard
Sources/en.lproj/Localizable.strings

The storyboard label of Discover was not changed nor the localisation strings.

Resolves #185 String bug in settings 

---

Sources/Models/API/OFFReadAPIkeysJSON.swift
Sources/Models/API/Product.swift

2nd part of multilingual products

The images are now localized as well.

---

Sources/Models/API/OFFReadAPIkeysJSON.swift
Sources/Models/API/Product.swift
Sources/Network/ProductService.swift

The new lc= approach to languages and the localized images work now.
-
-
-

Localized languages

---

README.md

Fixed subtitle formatting on string 58
-
-
-

Fixed subtitle formatting on string 58

---

Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift

* Make sure that the additive row isn’t created inline, but as a list
Describe the changes made and why they were made instead of how they were made.
- Update the display of the additives list following #60

 #60 - Display full name of additives, as a list

---

Sources/ViewControllers/Products/Search/SearchTableViewController.swift

Crash on startup IOS13
- [X ] Fixes Issue #343
See code

Crash on startup IOS13

---

Sources/ViewControllers/Products/Add/ProductAddViewController.swift

Solves product creation.
- [ X] Fixes Issue #325

Solves product creation

---

Sources/Extensions/RotatingProcessor.swift
Sources/Helpers/URLs.swift
Sources/Models/PersistenceManager.swift

see issue #358
- [X ] Fixes Issue #358
see code

Simple Xcode 11 warning repairs

---

Sources/Network/TaxonomiesService.swift

The "new" urls has a "/" to many.
- [X ] Fixes Issue #369

#369 corrected urls

---

README.md

Describe the changes made and why they were made instead of how they were made.
- Add back the (slightly reformatted to work within Xcode and on GitHub) README.md. 

Add back the README.md file

---

Sources/Assets.xcassets/nutriscore-a.imageset/Contents.json
Sources/Assets.xcassets/nutriscore-c.imageset/Contents.json
Sources/ViewControllers/Products/Add/EditNutritiveValueView.xib
Sources/ViewControllers/Products/Detail/Environment Impact/EnvironmentImpactTableFormTableViewController.swift
Sources/ViewControllers/Settings/CreditsViewController.swift
Sources/Views/LaunchScreen.storyboard
Sources/Views/Products/Add/ProductAddViewController.storyboard
Sources/Views/Products/Detail/Nutrition/NutritionHeaderTableViewCell.xib
Sources/Views/Products/Detail/Nutrition/NutritionLevelsTableViewCell.xib
Sources/Views/Products/Detail/NutritionTable/NutritionTableRowTableViewCell.xib
Sources/Views/Products/Detail/ProductDetailWebViewTableViewCell.xib
Sources/Views/Products/Search/StateViews/StateView.swift
Sources/Views/Settings/Settings.storyboard
Sources/Views/User/User.storyboard

Several dark more issues solved.

Dark mode details solved

---

OpenFoodFacts.xcodeproj/project.pbxproj
Sources/Views/Products/Add/ProductAddViewController.storyboard
Sources/Views/Products/Search/LoadingCell.xib

Set background of activity UI indicator to `.clear` and style to `.large`.
- [X ] Fixes Issue #407

#407 activity indicator now honoring dark mode

---

Sources/Views/Products/Detail/ProductDetailWebViewTableViewCell.swift
Sources/Views/Products/Detail/ProductDetailWebViewTableViewCell.xib

Solved the background and text colors of the nutrition web view

Issue 408 dark mode webview

---

Sources/ViewControllers/Products/Add/ProductAddViewController.swift

name and ingredients are now shown in edit mode.
- [X ] Fixes Issue #422

#422 name and ingredients are now shown in edit mode.

---

Sources/ViewControllers/Products/Detail/Summary/SummaryFooterCellController.swift

Workaround for #432 - Unresponsive view after ingredient cropping in Edit Mode proposed by @philippeauriach

Workaround for #432

---

OpenFoodFacts.xcodeproj/project.pbxproj
README.md

Added some dependency troubleshooting and more Carthage info, also updated the project wiki to troubleshoot this file :)
- Add Dependency troubleshooting and Carthage resources sections to the project README
- add README section to the project wiki Build page (done)

Added Carthage and README troubleshooting

---

Sources/Views/Products/Search/Scanner/ScanProductSummaryView.xib

Set backgrounds of NutriScore and Nova to` .clear`.
- [X ] Fixes Issue #431

#431 set backgrounds to .clear.

---

Sources/Models/API/OFFWriteAPI.swift

removed definition of SecureServer.
- [X ] Fixes Issue #446

446 removed definition of SecureServer

---

Sources/Views/User/User.storyboard

Added forgot password translations.

#443 added forgot password translations

---

Sources/ViewControllers/Products/Search/ScannerResultViewController.swift
Sources/ViewControllers/Products/Search/ScannerViewController.swift
Sources/Views/Products/Search/Scanner/ScanProductSummaryView.xib

#429 swipe down to hide floating panel

---

Sources/Models/API/ProductImage.swift
Sources/Models/PersistenceManager.swift
Sources/Models/Realm/RealmPendingUploadItem.swift
Sources/Models/ViewModel/PictureViewModel.swift
Sources/Network/ProductService.swift
Sources/ViewControllers/Camera/CameraController.swift
Sources/ViewControllers/Common/TakePictureViewController.swift

a new image is now assigned to the right language.

#458 a new image is now assigned to the right language.

---

Sources/Localization/en.lproj/Localizable.strings
Sources/Models/API/Product.swift
Sources/Models/Common/InfoRow.swift
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift

#59 added the generic name to the summary view

#59 added the generic name to the summary view

---

Sources/Helpers/SharingManager.swift
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift

#61 reinstalled share button
##Type of Changes

#61 reinstalled share button

---

OpenFoodFacts.xcodeproj/project.pbxproj
Sources/Network/ProductService.swift

#66 limited the fields in a product search query

#66 limited the fields in a product search query

---

OpenFoodFacts.xcodeproj/project.pbxproj

#464 did the migration

---

Sources/ViewControllers/User/PendingUploadTableViewController.swift
Sources/Views/User/User.storyboard

#466 introduced optional chaining

#466 introduced optional chaining

---

Sources/ViewControllers/User/LoggedInViewController.swift

#219 repaired contributions url when logged in with email address.

#219 repaired contributions url when logged in with email address.

---

Sources/Models/API/OFFReadAPIkeysJSON.swift

The traces were no longer shown as the values were not extracted from the json.
#245 Edited json keys for traces

#245 Edited json keys for traces

---

Sources/Localization/en.lproj/Localizable.strings
Sources/ViewControllers/Products/Detail/Ingredients/IngredientsHeaderCellController.swift
Sources/Views/Products/Detail/Ingredients/IngredientsHeaderCellController.xib

#475 - adapt nova strings

---

Sources/Localization/en.lproj/Localizable.strings

fix-nova-strings

---

Sources/ViewControllers/User/PendingUploadTableViewController.swift
Sources/Views/User/User.storyboard

#486 moved the tableView reloadData
##Type of Changes

#486 moved the tableView reloadData

---

Sources/AppDelegate.swift
Sources/Helpers/SharingManager.swift
Sources/Localization/en.lproj/Localizable.strings
Sources/Models/DataManager.swift
Sources/Models/HistoryItem.swift
Sources/Models/PendingProductMergeProcessor.swift
Sources/Models/PendingUploadItem.swift
Sources/Models/PersistenceManager.swift
Sources/Models/Realm/RealmOfflineProduct.swift
Sources/Models/Realm/RealmPendingUploadItem.swift
Sources/Network/OfflineProductsService.swift
Sources/ViewControllers/Products/Add/ProductAddViewController.swift
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift
Sources/Views/Products/Add/ProductAddViewController.storyboard

#491 editing packaging is now supported. Note that this requires a mig…ration of the Realm database. This will now be done automatically if the user starts this version. The necessary code for this is added in the AppDelegate.

#491 editing packaging is now supported

---

Sources/ViewControllers/Products/Add/ProductAddViewController.swift
Sources/ViewControllers/Products/Detail/Summary/SummaryFooterCellController.swift

Solved crash for loading non existing VC.

#496 solved crash

---

Sources/AppDelegate.swift
Sources/ViewControllers/Products/Add/ProductAddViewController.swift
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift
Sources/ViewControllers/Products/Search/ScannerViewController.swift

#220 user agent set for all http requests.

#220 user agent set for all http requests.

---

OpenFoodFacts.xcodeproj/project.pbxproj
OpenFoodFacts.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Sources/Helpers/OFFUrlsHelper.swift
Sources/Models/API/OFFReadAPIkeysJSON.swift
Sources/Models/API/Product.swift
Sources/Models/API/Taxonomies/Country.swift
Sources/Models/DataManager.swift
Sources/Models/PersistenceManager.swift
Sources/Network/TaxonomiesService.swift
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift

Countries_tags now used. This implies that `en:it` is now show as `Italy`.

Countries as tags

---

Sources/Views/Products/Detail/Ingredients/IngredientsHeaderCellController.xib

#507 Better scaling of nova explanation.

#507 Better scaling of nova explanation.

---

Sources/Models/API/Product.swift

#509 read novaGroup as int and string

#509 read novaGroup as int and string

---

Sources/Localization/en.lproj/Localizable.strings
Sources/Models/DataManager.swift

#508 logging in no longer worked. Have to use the standard userAgent for this. But this may be another issue than #508.

#508 logging in no longer worked.

---

OpenFoodFacts.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Sources/Models/Common/Form.swift
Sources/ViewControllers/Products/Detail/FormTableViewController.swift
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift

nicer tap through to site pages

#519 nicer tap through to site pages

---

OpenFoodFacts.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Sources/Views/Products/Detail/Ingredients/IngredientsHeaderCellController.xib

limit the maximum height of the NOVA image

#520 limit the maximum height of the NOVA image

---

OpenFoodFacts.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Sources/ViewControllers/Products/Add/ProductAddViewController.swift
Sources/ViewControllers/Products/Detail/Summary/SummaryFooterCellController.swift
Sources/ViewControllers/Products/Search/ScannerViewController.swift

nutriments are now saved as well.

#512 nutriments are now saved as well.

---

OpenFoodFacts.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Sources/Localization/en.lproj/Localizable.strings
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift

nicer fall back if there are no nutrients.

#517 nicer fall back if there are no nutrients.

---

Sources/AppDelegate.swift
Sources/ViewControllers/Products/Add/ProductAddViewController.swift
Sources/ViewControllers/Products/Detail/FormTableViewController.swift
Sources/ViewControllers/Products/Detail/Summary/SummaryFooterCellController.swift
Sources/ViewControllers/Products/Search/ScannerViewController.swift

#533 added selector check

---

Sources/ViewControllers/User/UserViewController.swift

#545 login button is always enabled.

#545 login button is always enabled.

---

OpenFoodFacts.xcodeproj/project.pbxproj
OpenFoodFacts.xcodeproj/xcshareddata/xcschemes/OpenFoodFacts.xcscheme
Sources/AppDelegate.swift
Sources/Models/API/Taxonomies/Tagline.swift
Sources/Models/DataManager.swift
Sources/Models/PersistenceManager.swift
Sources/Network/OfflineProductsService.swift
Sources/Network/TaxonomiesService.swift
Sources/ViewControllers/Products/Search/SearchTableViewController.swift
Sources/Views/Products/Search/StateViews/InitialView.swift
Sources/Views/Products/Search/StateViews/InitialView.xib
Tests/Common/DataManagerMock.swift

Proposed changes: in home "viewwillappear"
- display the latest tagline in local cache
- update the local cache with distant tagline
- refresh displayed tagline with latest version

Feature/promo system home #154

---

OpenFoodFacts.xcodeproj/project.pbxproj
Sources/Extensions/String.swift
Sources/Info.plist
Sources/ViewControllers/Products/Search/HistoryTableViewController.swift

Revert html decoder, as it hangs the application

Revert html decoder, as it hangs the application

---

Sources/Views/Products/Detail/Ingredients/RobotoffQuestionTableViewCell.swift

adapted Hunger confirm buttons to dark mode.

#603 adapted Hunger confirm buttons to dark mode.

---

Sources/Views/Products/Detail/Common/IngredientsAnalysisView.swift
Sources/Views/Products/Detail/Ingredients/RobotoffQuestionTableViewCell.swift

Trying to prevent the BLTNBoard crash.
Not sure this will work 100%, but it might reduce the number of rashes.

#591 Trying to prevent the BLTNBoard crash

---

Sources/Views/Products/Detail/Common/IngredientsAnalysisView.swift

fix padding of ingredients analysis switch label Fix #585

---

Sources/Helpers/OFFUrlsHelper.swift
Sources/ViewControllers/Products/Search/SearchTableViewController.swift

Added optionals to circumvent crash #609.

#609 added optionals.

---

Sources/Views/Products/Detail/Ingredients/RobotoffQuestionTableViewCell.swift

finally was able to test a robotoff question. Did some finetuning.
#603

#603 finally was able to test a robotoff question. Did some finetuning.

---

Sources/Helpers/SharingManager.swift
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift

#573 added an open in Safari share activity

#573 added an open in Safari share activity

---

Sources/Extensions/String.swift
Sources/Helpers/SharingManager.swift
Sources/ViewControllers/Camera/CameraController.swift
Sources/ViewControllers/Common/TakePictureViewController.swift
Sources/ViewControllers/Products/Detail/FormTableViewController.swift
Sources/ViewControllers/Products/Detail/Ingredients/IngredientsHeaderCellController.swift
Sources/ViewControllers/Products/Detail/NutritionTable/NutritionTableHeaderCellController.swift
Sources/ViewControllers/Products/Detail/ProductDetailViewController.swift
Sources/ViewControllers/Products/Detail/Summary/SummaryHeaderCellController.swift
Sources/ViewControllers/Products/Search/HistoryTableViewController.swift
Sources/Views/Products/Detail/Common/IngredientsAnalysisView.swift

#620 better image uploading. I recreated the branch.

#620 better image uploading
